Numpy함수 학습

In [1]:
#np.array():numpy 배열을 생성하는 함수
import numpy as np

#리스트를 numpy 배열로 변환
arr=np.array([1,2,3,4,5]);
print(arr);


[1 2 3 4 5]


In [ ]:
#np.arange(): 지정된 범위 내에서 일정 간격으로 값을 생성하는 함수   
    #start부터 stop까지 step간격으로 값을 생성

#0부터 9까지의 정수 배열 생성
arr=np.arange(10);
print(arr);

#0부터 10까지 2간격으로 생성
arr2=np.arange(0,10,2);
print(arr2);

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
#np.linspace(): 주어진 구간을 일정한 간격으로 나누어 값을 생성하는 함수
    #start와 stop사이를 num개의 균등 간격으로 나누어 값을 생성

#0부터 1까지 5개의 균등한 간격의 값 생성
arr=np.linspace(0,1,5);
print(arr);

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#np.random.random(): 0과 1 사이의 난수를 생성하는 함수

arr=np.random.random((2,3));
print(arr);

[[0.23199891 0.64795154 0.68833913]
 [0.64668786 0.56381232 0.19245183]]


In [ ]:
#np.zeros(): 모든 요소가 0인 배열을 생성하는 함수

#3*3 크기의 0으로 채워진 배열 생성
arr=np.zeros((3,3));
print(arr);

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.sum(): 배열의 합을 구하는 함수

#배열 생성
arr=np.array([1,2,3,4,5]);

#배열의 합 계산
total=np.sum(arr);
print(total);

#2D 배열에서 각 열의 합 계산
arr2=np.array([[1,2,3],[4,5,6]]);
column_sum=np.sum(arr2,axis=0);
print(column_sum);

15
[5 7 9]


In [ ]:
#np.mean(): 배열의 평균을 구하는 함수

#배열 생성
arr=np.array([1,2,3,4,5]);

#배열의 평균값 계산
mean_value=np.mean(arr);
print(mean_value);

3.0


In [ ]:
#np.reshape(): 배열의 모양을 변경하는 함수

#1D 배열 생성
arr=np.array([1,2,3,4,5,6]);

#2*3 배열로 변환
reshaped_arr=np.reshape(arr,(2,3));
print(reshaped_arr);

[[1 2 3]
 [4 5 6]]


In [ ]:
#np.dot(): 두 배열의 행렬 곱을 계산하는 함수

#두 배열 생성
arr1=np.array([1,2]);
arr2=np.array([3,4]);

#내적 계산
dot_product=np.dot(arr1,arr2);
print(dot_product);

11


In [ ]:
#np.transpose(): 배열을 전치하는 함수
#2D 배열 생성
arr=np.array([[1,2,3],[4,5,6]]);

#배열 전치
transposed_arr=np.transpose(arr);
print(transposed_arr);


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#np.unique(): 배열에서 고유한 값을 반환하는 함수

#배열 생성
arr=np.array([1,2,2,3,3,3,4]);

#고유한 값 구하기
unique_values=np.unique(arr);
print(unique_values);


[1 2 3 4]
